name: Publish Chart

on:
  push:
    branches:
      - master

jobs:
  publish:
    permissions:
      contents: write
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout
        with:
          fetch-depth: 0
      - name: Configure git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
      - name: Install helm
        uses: azure/helm
        with:
          version: v3.10.3
      - name: Run chart-releaser
        uses: helm/chart-releaser-action
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
